// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: tinypenguin/common.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: tinypenguin/common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ToolUseResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                 // "success", "error", "denied"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                               // Human-readable message
	ToolName      string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`             // Name of the tool that was executed
	ToolOutput    string                 `protobuf:"bytes,4,opt,name=tool_output,json=toolOutput,proto3" json:"tool_output,omitempty"`       // Output from the tool execution
	ErrorDetails  string                 `protobuf:"bytes,5,opt,name=error_details,json=errorDetails,proto3" json:"error_details,omitempty"` // Detailed error information if status is "error"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolUseResult) Reset() {
	*x = ToolUseResult{}
	mi := &file_tinypenguin_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolUseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolUseResult) ProtoMessage() {}

func (x *ToolUseResult) ProtoReflect() protoreflect.Message {
	mi := &file_tinypenguin_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolUseResult.ProtoReflect.Descriptor instead.
func (*ToolUseResult) Descriptor() ([]byte, []int) {
	return file_tinypenguin_common_proto_rawDescGZIP(), []int{0}
}

func (x *ToolUseResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ToolUseResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ToolUseResult) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolUseResult) GetToolOutput() string {
	if x != nil {
		return x.ToolOutput
	}
	return ""
}

func (x *ToolUseResult) GetErrorDetails() string {
	if x != nil {
		return x.ErrorDetails
	}
	return ""
}

type TinyllamaRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Model          string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`                                                                                 // Model name for tinyllama
	Prompt         string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`                                                                               // The prompt to send to tinyllama
	AvailableTools []*ToolDefinition      `protobuf:"bytes,3,rep,name=available_tools,json=availableTools,proto3" json:"available_tools,omitempty"`                                         // Tools available to the model
	Metadata       map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TinyllamaRequest) Reset() {
	*x = TinyllamaRequest{}
	mi := &file_tinypenguin_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TinyllamaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TinyllamaRequest) ProtoMessage() {}

func (x *TinyllamaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tinypenguin_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TinyllamaRequest.ProtoReflect.Descriptor instead.
func (*TinyllamaRequest) Descriptor() ([]byte, []int) {
	return file_tinypenguin_common_proto_rawDescGZIP(), []int{1}
}

func (x *TinyllamaRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *TinyllamaRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *TinyllamaRequest) GetAvailableTools() []*ToolDefinition {
	if x != nil {
		return x.AvailableTools
	}
	return nil
}

func (x *TinyllamaRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TinyllamaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                                  // Response content from tinyllama
	HasToolCalls  bool                   `protobuf:"varint,2,opt,name=has_tool_calls,json=hasToolCalls,proto3" json:"has_tool_calls,omitempty"` // Whether the response contains tool calls
	ToolCalls     []*ToolCall            `protobuf:"bytes,3,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`             // Tool calls made by the model
	FinishReason  string                 `protobuf:"bytes,4,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`    // Why the response finished (stop, length, tool_calls, etc.)
	UsageTokens   int32                  `protobuf:"varint,5,opt,name=usage_tokens,json=usageTokens,proto3" json:"usage_tokens,omitempty"`      // Number of tokens used
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TinyllamaResponse) Reset() {
	*x = TinyllamaResponse{}
	mi := &file_tinypenguin_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TinyllamaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TinyllamaResponse) ProtoMessage() {}

func (x *TinyllamaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tinypenguin_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TinyllamaResponse.ProtoReflect.Descriptor instead.
func (*TinyllamaResponse) Descriptor() ([]byte, []int) {
	return file_tinypenguin_common_proto_rawDescGZIP(), []int{2}
}

func (x *TinyllamaResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TinyllamaResponse) GetHasToolCalls() bool {
	if x != nil {
		return x.HasToolCalls
	}
	return false
}

func (x *TinyllamaResponse) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *TinyllamaResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *TinyllamaResponse) GetUsageTokens() int32 {
	if x != nil {
		return x.UsageTokens
	}
	return 0
}

type ToolDefinition struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Name          string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                                       // Tool name
	Description   string                    `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                                                                         // Tool description
	Parameters    map[string]*ToolParameter `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Tool parameters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_tinypenguin_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_tinypenguin_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_tinypenguin_common_proto_rawDescGZIP(), []int{3}
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetParameters() map[string]*ToolParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ToolParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`               // Parameter type (string, number, boolean, etc.)
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // Parameter description
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`      // Whether this parameter is required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolParameter) Reset() {
	*x = ToolParameter{}
	mi := &file_tinypenguin_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolParameter) ProtoMessage() {}

func (x *ToolParameter) ProtoReflect() protoreflect.Message {
	mi := &file_tinypenguin_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolParameter.ProtoReflect.Descriptor instead.
func (*ToolParameter) Descriptor() ([]byte, []int) {
	return file_tinypenguin_common_proto_rawDescGZIP(), []int{4}
}

func (x *ToolParameter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolParameter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolParameter) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                         // Unique identifier for this tool call
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                                     // Tool name being called
	Arguments     map[string]string      `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Arguments for the tool call
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_tinypenguin_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_tinypenguin_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_tinypenguin_common_proto_rawDescGZIP(), []int{5}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArguments() map[string]string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type FileOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // File path
	// Types that are valid to be assigned to Operation:
	//
	//	*FileOperation_Content
	//	*FileOperation_Diff
	Operation     isFileOperation_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileOperation) Reset() {
	*x = FileOperation{}
	mi := &file_tinypenguin_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOperation) ProtoMessage() {}

func (x *FileOperation) ProtoReflect() protoreflect.Message {
	mi := &file_tinypenguin_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOperation.ProtoReflect.Descriptor instead.
func (*FileOperation) Descriptor() ([]byte, []int) {
	return file_tinypenguin_common_proto_rawDescGZIP(), []int{6}
}

func (x *FileOperation) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileOperation) GetOperation() isFileOperation_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *FileOperation) GetContent() string {
	if x != nil {
		if x, ok := x.Operation.(*FileOperation_Content); ok {
			return x.Content
		}
	}
	return ""
}

func (x *FileOperation) GetDiff() string {
	if x != nil {
		if x, ok := x.Operation.(*FileOperation_Diff); ok {
			return x.Diff
		}
	}
	return ""
}

type isFileOperation_Operation interface {
	isFileOperation_Operation()
}

type FileOperation_Content struct {
	Content string `protobuf:"bytes,2,opt,name=content,proto3,oneof"` // Direct content for write operations
}

type FileOperation_Diff struct {
	Diff string `protobuf:"bytes,3,opt,name=diff,proto3,oneof"` // Diff content for replace operations
}

func (*FileOperation_Content) isFileOperation_Operation() {}

func (*FileOperation_Diff) isFileOperation_Operation() {}

type CommandOperation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Command          string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`                                            // Command to execute
	WorkingDirectory string                 `protobuf:"bytes,2,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`  // Working directory (optional)
	TimeoutSeconds   int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`       // Timeout in seconds (optional)
	RequiresApproval bool                   `protobuf:"varint,4,opt,name=requires_approval,json=requiresApproval,proto3" json:"requires_approval,omitempty"` // Whether this command requires user approval
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CommandOperation) Reset() {
	*x = CommandOperation{}
	mi := &file_tinypenguin_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandOperation) ProtoMessage() {}

func (x *CommandOperation) ProtoReflect() protoreflect.Message {
	mi := &file_tinypenguin_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandOperation.ProtoReflect.Descriptor instead.
func (*CommandOperation) Descriptor() ([]byte, []int) {
	return file_tinypenguin_common_proto_rawDescGZIP(), []int{7}
}

func (x *CommandOperation) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandOperation) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

func (x *CommandOperation) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *CommandOperation) GetRequiresApproval() bool {
	if x != nil {
		return x.RequiresApproval
	}
	return false
}

// Configuration for RHCSA/bash operations
type RHCSAConfig struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	EnablePrivilegedCommands bool                   `protobuf:"varint,1,opt,name=enable_privileged_commands,json=enablePrivilegedCommands,proto3" json:"enable_privileged_commands,omitempty"` // Allow sudo commands
	AllowedPackages          []string               `protobuf:"bytes,2,rep,name=allowed_packages,json=allowedPackages,proto3" json:"allowed_packages,omitempty"`                               // Package names that can be installed
	ProtectedPaths           []string               `protobuf:"bytes,3,rep,name=protected_paths,json=protectedPaths,proto3" json:"protected_paths,omitempty"`                                  // Paths that require extra approval
	RequireCommandValidation bool                   `protobuf:"varint,4,opt,name=require_command_validation,json=requireCommandValidation,proto3" json:"require_command_validation,omitempty"` // Validate commands before execution
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RHCSAConfig) Reset() {
	*x = RHCSAConfig{}
	mi := &file_tinypenguin_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RHCSAConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RHCSAConfig) ProtoMessage() {}

func (x *RHCSAConfig) ProtoReflect() protoreflect.Message {
	mi := &file_tinypenguin_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RHCSAConfig.ProtoReflect.Descriptor instead.
func (*RHCSAConfig) Descriptor() ([]byte, []int) {
	return file_tinypenguin_common_proto_rawDescGZIP(), []int{8}
}

func (x *RHCSAConfig) GetEnablePrivilegedCommands() bool {
	if x != nil {
		return x.EnablePrivilegedCommands
	}
	return false
}

func (x *RHCSAConfig) GetAllowedPackages() []string {
	if x != nil {
		return x.AllowedPackages
	}
	return nil
}

func (x *RHCSAConfig) GetProtectedPaths() []string {
	if x != nil {
		return x.ProtectedPaths
	}
	return nil
}

func (x *RHCSAConfig) GetRequireCommandValidation() bool {
	if x != nil {
		return x.RequireCommandValidation
	}
	return false
}

var File_tinypenguin_common_proto protoreflect.FileDescriptor

const file_tinypenguin_common_proto_rawDesc = "" +
	"\n" +
	"\x18tinypenguin/common.proto\x12\vtinypenguin\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa4\x01\n" +
	"\rToolUseResult\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12\x1f\n" +
	"\vtool_output\x18\x04 \x01(\tR\n" +
	"toolOutput\x12#\n" +
	"\rerror_details\x18\x05 \x01(\tR\ferrorDetails\"\x8c\x02\n" +
	"\x10TinyllamaRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12D\n" +
	"\x0favailable_tools\x18\x03 \x03(\v2\x1b.tinypenguin.ToolDefinitionR\x0eavailableTools\x12G\n" +
	"\bmetadata\x18\x04 \x03(\v2+.tinypenguin.TinyllamaRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd1\x01\n" +
	"\x11TinyllamaResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12$\n" +
	"\x0ehas_tool_calls\x18\x02 \x01(\bR\fhasToolCalls\x124\n" +
	"\n" +
	"tool_calls\x18\x03 \x03(\v2\x15.tinypenguin.ToolCallR\ttoolCalls\x12#\n" +
	"\rfinish_reason\x18\x04 \x01(\tR\ffinishReason\x12!\n" +
	"\fusage_tokens\x18\x05 \x01(\x05R\vusageTokens\"\xee\x01\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12K\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2+.tinypenguin.ToolDefinition.ParametersEntryR\n" +
	"parameters\x1aY\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.tinypenguin.ToolParameterR\x05value:\x028\x01\"a\n" +
	"\rToolParameter\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\"\xb0\x01\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12B\n" +
	"\targuments\x18\x03 \x03(\v2$.tinypenguin.ToolCall.ArgumentsEntryR\targuments\x1a<\n" +
	"\x0eArgumentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"b\n" +
	"\rFileOperation\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\acontent\x18\x02 \x01(\tH\x00R\acontent\x12\x14\n" +
	"\x04diff\x18\x03 \x01(\tH\x00R\x04diffB\v\n" +
	"\toperation\"\xaf\x01\n" +
	"\x10CommandOperation\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12+\n" +
	"\x11working_directory\x18\x02 \x01(\tR\x10workingDirectory\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\x12+\n" +
	"\x11requires_approval\x18\x04 \x01(\bR\x10requiresApproval\"\xdd\x01\n" +
	"\vRHCSAConfig\x12<\n" +
	"\x1aenable_privileged_commands\x18\x01 \x01(\bR\x18enablePrivilegedCommands\x12)\n" +
	"\x10allowed_packages\x18\x02 \x03(\tR\x0fallowedPackages\x12'\n" +
	"\x0fprotected_paths\x18\x03 \x03(\tR\x0eprotectedPaths\x12<\n" +
	"\x1arequire_command_validation\x18\x04 \x01(\bR\x18requireCommandValidationB-Z+github.com/anthropic-cli/tinypenguin/pkg/pbb\x06proto3"

var (
	file_tinypenguin_common_proto_rawDescOnce sync.Once
	file_tinypenguin_common_proto_rawDescData []byte
)

func file_tinypenguin_common_proto_rawDescGZIP() []byte {
	file_tinypenguin_common_proto_rawDescOnce.Do(func() {
		file_tinypenguin_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tinypenguin_common_proto_rawDesc), len(file_tinypenguin_common_proto_rawDesc)))
	})
	return file_tinypenguin_common_proto_rawDescData
}

var file_tinypenguin_common_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_tinypenguin_common_proto_goTypes = []any{
	(*ToolUseResult)(nil),     // 0: tinypenguin.ToolUseResult
	(*TinyllamaRequest)(nil),  // 1: tinypenguin.TinyllamaRequest
	(*TinyllamaResponse)(nil), // 2: tinypenguin.TinyllamaResponse
	(*ToolDefinition)(nil),    // 3: tinypenguin.ToolDefinition
	(*ToolParameter)(nil),     // 4: tinypenguin.ToolParameter
	(*ToolCall)(nil),          // 5: tinypenguin.ToolCall
	(*FileOperation)(nil),     // 6: tinypenguin.FileOperation
	(*CommandOperation)(nil),  // 7: tinypenguin.CommandOperation
	(*RHCSAConfig)(nil),       // 8: tinypenguin.RHCSAConfig
	nil,                       // 9: tinypenguin.TinyllamaRequest.MetadataEntry
	nil,                       // 10: tinypenguin.ToolDefinition.ParametersEntry
	nil,                       // 11: tinypenguin.ToolCall.ArgumentsEntry
}
var file_tinypenguin_common_proto_depIdxs = []int32{
	3,  // 0: tinypenguin.TinyllamaRequest.available_tools:type_name -> tinypenguin.ToolDefinition
	9,  // 1: tinypenguin.TinyllamaRequest.metadata:type_name -> tinypenguin.TinyllamaRequest.MetadataEntry
	5,  // 2: tinypenguin.TinyllamaResponse.tool_calls:type_name -> tinypenguin.ToolCall
	10, // 3: tinypenguin.ToolDefinition.parameters:type_name -> tinypenguin.ToolDefinition.ParametersEntry
	11, // 4: tinypenguin.ToolCall.arguments:type_name -> tinypenguin.ToolCall.ArgumentsEntry
	4,  // 5: tinypenguin.ToolDefinition.ParametersEntry.value:type_name -> tinypenguin.ToolParameter
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_tinypenguin_common_proto_init() }
func file_tinypenguin_common_proto_init() {
	if File_tinypenguin_common_proto != nil {
		return
	}
	file_tinypenguin_common_proto_msgTypes[6].OneofWrappers = []any{
		(*FileOperation_Content)(nil),
		(*FileOperation_Diff)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tinypenguin_common_proto_rawDesc), len(file_tinypenguin_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tinypenguin_common_proto_goTypes,
		DependencyIndexes: file_tinypenguin_common_proto_depIdxs,
		MessageInfos:      file_tinypenguin_common_proto_msgTypes,
	}.Build()
	File_tinypenguin_common_proto = out.File
	file_tinypenguin_common_proto_goTypes = nil
	file_tinypenguin_common_proto_depIdxs = nil
}
