// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: tinypenguin/task.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: tinypenguin/task.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_RUNNING     TaskStatus = 1
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 2
	TaskStatus_TASK_STATUS_CANCELLED   TaskStatus = 3
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 4
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_RUNNING",
		2: "TASK_STATUS_COMPLETED",
		3: "TASK_STATUS_CANCELLED",
		4: "TASK_STATUS_FAILED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_RUNNING":     1,
		"TASK_STATUS_COMPLETED":   2,
		"TASK_STATUS_CANCELLED":   3,
		"TASK_STATUS_FAILED":      4,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tinypenguin_task_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_tinypenguin_task_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_tinypenguin_task_proto_rawDescGZIP(), []int{0}
}

type ExecuteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTaskRequest) Reset() {
	*x = ExecuteTaskRequest{}
	mi := &file_tinypenguin_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskRequest) ProtoMessage() {}

func (x *ExecuteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tinypenguin_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskRequest.ProtoReflect.Descriptor instead.
func (*ExecuteTaskRequest) Descriptor() ([]byte, []int) {
	return file_tinypenguin_task_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteTaskRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type ExecuteTaskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ExecuteTaskResponse_TaskStarted
	//	*ExecuteTaskResponse_TaskOutput
	//	*ExecuteTaskResponse_TaskCompleted
	//	*ExecuteTaskResponse_TaskError
	Response      isExecuteTaskResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTaskResponse) Reset() {
	*x = ExecuteTaskResponse{}
	mi := &file_tinypenguin_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskResponse) ProtoMessage() {}

func (x *ExecuteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tinypenguin_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskResponse.ProtoReflect.Descriptor instead.
func (*ExecuteTaskResponse) Descriptor() ([]byte, []int) {
	return file_tinypenguin_task_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteTaskResponse) GetResponse() isExecuteTaskResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ExecuteTaskResponse) GetTaskStarted() *TaskStarted {
	if x != nil {
		if x, ok := x.Response.(*ExecuteTaskResponse_TaskStarted); ok {
			return x.TaskStarted
		}
	}
	return nil
}

func (x *ExecuteTaskResponse) GetTaskOutput() *TaskOutput {
	if x != nil {
		if x, ok := x.Response.(*ExecuteTaskResponse_TaskOutput); ok {
			return x.TaskOutput
		}
	}
	return nil
}

func (x *ExecuteTaskResponse) GetTaskCompleted() *TaskCompleted {
	if x != nil {
		if x, ok := x.Response.(*ExecuteTaskResponse_TaskCompleted); ok {
			return x.TaskCompleted
		}
	}
	return nil
}

func (x *ExecuteTaskResponse) GetTaskError() *TaskError {
	if x != nil {
		if x, ok := x.Response.(*ExecuteTaskResponse_TaskError); ok {
			return x.TaskError
		}
	}
	return nil
}

type isExecuteTaskResponse_Response interface {
	isExecuteTaskResponse_Response()
}

type ExecuteTaskResponse_TaskStarted struct {
	TaskStarted *TaskStarted `protobuf:"bytes,1,opt,name=task_started,json=taskStarted,proto3,oneof"`
}

type ExecuteTaskResponse_TaskOutput struct {
	TaskOutput *TaskOutput `protobuf:"bytes,2,opt,name=task_output,json=taskOutput,proto3,oneof"`
}

type ExecuteTaskResponse_TaskCompleted struct {
	TaskCompleted *TaskCompleted `protobuf:"bytes,3,opt,name=task_completed,json=taskCompleted,proto3,oneof"`
}

type ExecuteTaskResponse_TaskError struct {
	TaskError *TaskError `protobuf:"bytes,4,opt,name=task_error,json=taskError,proto3,oneof"`
}

func (*ExecuteTaskResponse_TaskStarted) isExecuteTaskResponse_Response() {}

func (*ExecuteTaskResponse_TaskOutput) isExecuteTaskResponse_Response() {}

func (*ExecuteTaskResponse_TaskCompleted) isExecuteTaskResponse_Response() {}

func (*ExecuteTaskResponse_TaskError) isExecuteTaskResponse_Response() {}

type TaskStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStarted) Reset() {
	*x = TaskStarted{}
	mi := &file_tinypenguin_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStarted) ProtoMessage() {}

func (x *TaskStarted) ProtoReflect() protoreflect.Message {
	mi := &file_tinypenguin_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStarted.ProtoReflect.Descriptor instead.
func (*TaskStarted) Descriptor() ([]byte, []int) {
	return file_tinypenguin_task_proto_rawDescGZIP(), []int{2}
}

func (x *TaskStarted) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskOutput) Reset() {
	*x = TaskOutput{}
	mi := &file_tinypenguin_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOutput) ProtoMessage() {}

func (x *TaskOutput) ProtoReflect() protoreflect.Message {
	mi := &file_tinypenguin_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOutput.ProtoReflect.Descriptor instead.
func (*TaskOutput) Descriptor() ([]byte, []int) {
	return file_tinypenguin_task_proto_rawDescGZIP(), []int{3}
}

func (x *TaskOutput) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type TaskCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCompleted) Reset() {
	*x = TaskCompleted{}
	mi := &file_tinypenguin_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompleted) ProtoMessage() {}

func (x *TaskCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_tinypenguin_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompleted.ProtoReflect.Descriptor instead.
func (*TaskCompleted) Descriptor() ([]byte, []int) {
	return file_tinypenguin_task_proto_rawDescGZIP(), []int{4}
}

func (x *TaskCompleted) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type TaskError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskError) Reset() {
	*x = TaskError{}
	mi := &file_tinypenguin_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskError) ProtoMessage() {}

func (x *TaskError) ProtoReflect() protoreflect.Message {
	mi := &file_tinypenguin_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskError.ProtoReflect.Descriptor instead.
func (*TaskError) Descriptor() ([]byte, []int) {
	return file_tinypenguin_task_proto_rawDescGZIP(), []int{5}
}

func (x *TaskError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_tinypenguin_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tinypenguin_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_tinypenguin_task_proto_rawDescGZIP(), []int{6}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_tinypenguin_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tinypenguin_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_tinypenguin_task_proto_rawDescGZIP(), []int{7}
}

func (x *CancelTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_tinypenguin_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tinypenguin_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_tinypenguin_task_proto_rawDescGZIP(), []int{8}
}

func (x *ListTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTasksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_tinypenguin_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tinypenguin_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_tinypenguin_task_proto_rawDescGZIP(), []int{9}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Status        TaskStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=tinypenguin.TaskStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_tinypenguin_task_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_tinypenguin_task_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_tinypenguin_task_proto_rawDescGZIP(), []int{10}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_tinypenguin_task_proto protoreflect.FileDescriptor

const file_tinypenguin_task_proto_rawDesc = "" +
	"\n" +
	"\x16tinypenguin/task.proto\x12\vtinypenguin\x1a\x18tinypenguin/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"*\n" +
	"\x12ExecuteTaskRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"\x9a\x02\n" +
	"\x13ExecuteTaskResponse\x12=\n" +
	"\ftask_started\x18\x01 \x01(\v2\x18.tinypenguin.TaskStartedH\x00R\vtaskStarted\x12:\n" +
	"\vtask_output\x18\x02 \x01(\v2\x17.tinypenguin.TaskOutputH\x00R\n" +
	"taskOutput\x12C\n" +
	"\x0etask_completed\x18\x03 \x01(\v2\x1a.tinypenguin.TaskCompletedH\x00R\rtaskCompleted\x127\n" +
	"\n" +
	"task_error\x18\x04 \x01(\v2\x16.tinypenguin.TaskErrorH\x00R\ttaskErrorB\n" +
	"\n" +
	"\bresponse\"&\n" +
	"\vTaskStarted\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"$\n" +
	"\n" +
	"TaskOutput\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\"'\n" +
	"\rTaskCompleted\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"!\n" +
	"\tTaskError\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\",\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\".\n" +
	"\x12CancelTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"N\n" +
	"\x10ListTasksRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"d\n" +
	"\x11ListTasksResponse\x12'\n" +
	"\x05tasks\x18\x01 \x03(\v2\x11.tinypenguin.TaskR\x05tasks\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xa1\x01\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12/\n" +
	"\x06status\x18\x03 \x01(\x0e2\x17.tinypenguin.TaskStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*\x90\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x01\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x02\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\x03\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x042\x82\x02\n" +
	"\vTaskService\x12T\n" +
	"\vExecuteTask\x12\x1f.tinypenguin.ExecuteTaskRequest\x1a .tinypenguin.ExecuteTaskResponse\"\x000\x01\x12O\n" +
	"\n" +
	"CancelTask\x12\x1e.tinypenguin.CancelTaskRequest\x1a\x1f.tinypenguin.CancelTaskResponse\"\x00\x12L\n" +
	"\tListTasks\x12\x1d.tinypenguin.ListTasksRequest\x1a\x1e.tinypenguin.ListTasksResponse\"\x00B-Z+github.com/anthropic-cli/tinypenguin/pkg/pbb\x06proto3"

var (
	file_tinypenguin_task_proto_rawDescOnce sync.Once
	file_tinypenguin_task_proto_rawDescData []byte
)

func file_tinypenguin_task_proto_rawDescGZIP() []byte {
	file_tinypenguin_task_proto_rawDescOnce.Do(func() {
		file_tinypenguin_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tinypenguin_task_proto_rawDesc), len(file_tinypenguin_task_proto_rawDesc)))
	})
	return file_tinypenguin_task_proto_rawDescData
}

var file_tinypenguin_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tinypenguin_task_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_tinypenguin_task_proto_goTypes = []any{
	(TaskStatus)(0),               // 0: tinypenguin.TaskStatus
	(*ExecuteTaskRequest)(nil),    // 1: tinypenguin.ExecuteTaskRequest
	(*ExecuteTaskResponse)(nil),   // 2: tinypenguin.ExecuteTaskResponse
	(*TaskStarted)(nil),           // 3: tinypenguin.TaskStarted
	(*TaskOutput)(nil),            // 4: tinypenguin.TaskOutput
	(*TaskCompleted)(nil),         // 5: tinypenguin.TaskCompleted
	(*TaskError)(nil),             // 6: tinypenguin.TaskError
	(*CancelTaskRequest)(nil),     // 7: tinypenguin.CancelTaskRequest
	(*CancelTaskResponse)(nil),    // 8: tinypenguin.CancelTaskResponse
	(*ListTasksRequest)(nil),      // 9: tinypenguin.ListTasksRequest
	(*ListTasksResponse)(nil),     // 10: tinypenguin.ListTasksResponse
	(*Task)(nil),                  // 11: tinypenguin.Task
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_tinypenguin_task_proto_depIdxs = []int32{
	3,  // 0: tinypenguin.ExecuteTaskResponse.task_started:type_name -> tinypenguin.TaskStarted
	4,  // 1: tinypenguin.ExecuteTaskResponse.task_output:type_name -> tinypenguin.TaskOutput
	5,  // 2: tinypenguin.ExecuteTaskResponse.task_completed:type_name -> tinypenguin.TaskCompleted
	6,  // 3: tinypenguin.ExecuteTaskResponse.task_error:type_name -> tinypenguin.TaskError
	11, // 4: tinypenguin.ListTasksResponse.tasks:type_name -> tinypenguin.Task
	0,  // 5: tinypenguin.Task.status:type_name -> tinypenguin.TaskStatus
	12, // 6: tinypenguin.Task.created_at:type_name -> google.protobuf.Timestamp
	1,  // 7: tinypenguin.TaskService.ExecuteTask:input_type -> tinypenguin.ExecuteTaskRequest
	7,  // 8: tinypenguin.TaskService.CancelTask:input_type -> tinypenguin.CancelTaskRequest
	9,  // 9: tinypenguin.TaskService.ListTasks:input_type -> tinypenguin.ListTasksRequest
	2,  // 10: tinypenguin.TaskService.ExecuteTask:output_type -> tinypenguin.ExecuteTaskResponse
	8,  // 11: tinypenguin.TaskService.CancelTask:output_type -> tinypenguin.CancelTaskResponse
	10, // 12: tinypenguin.TaskService.ListTasks:output_type -> tinypenguin.ListTasksResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_tinypenguin_task_proto_init() }
func file_tinypenguin_task_proto_init() {
	if File_tinypenguin_task_proto != nil {
		return
	}
	file_tinypenguin_common_proto_init()
	file_tinypenguin_task_proto_msgTypes[1].OneofWrappers = []any{
		(*ExecuteTaskResponse_TaskStarted)(nil),
		(*ExecuteTaskResponse_TaskOutput)(nil),
		(*ExecuteTaskResponse_TaskCompleted)(nil),
		(*ExecuteTaskResponse_TaskError)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tinypenguin_task_proto_rawDesc), len(file_tinypenguin_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tinypenguin_task_proto_goTypes,
		DependencyIndexes: file_tinypenguin_task_proto_depIdxs,
		EnumInfos:         file_tinypenguin_task_proto_enumTypes,
		MessageInfos:      file_tinypenguin_task_proto_msgTypes,
	}.Build()
	File_tinypenguin_task_proto = out.File
	file_tinypenguin_task_proto_goTypes = nil
	file_tinypenguin_task_proto_depIdxs = nil
}
